# Generated by Django 4.2 on 2023-04-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='comment',
            field=models.CharField(default='Not available', max_length=70),
        ),
    ]
